name: Deploy to s3

on:
  push:
     branches: [main]

jobs:
   deploy:
       runs-on: ubuntu-latest

       steps:
           -name: Checkout code
            uses: actions/checkout@v3

           -name: Setup nodejs
            uses: actions/setup-nodejs@v3

           -name: Install dependencies
            run: npm ci

          -name: Build project
           run: npm run build  